language: python
matrix:
  include:
  - os: linux
    sudo: false
    dist: trusty
    python: '2.7'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.4'
  - os: linux
    sudo: false
    dist: trusty
    python: '3.5'
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.5
before_install:
- wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh
  -O install.sh
- chmod +x install.sh
- travis_retry bash -x ./install.sh
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
before_script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py test
script:
- export PATH="$HOME/miniconda/bin:$PATH"
- source activate travisci
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import ncephes; ncephes.test()"
- popd
branches:
  only:
  - master
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: j1p1tRRECv9zXMoaE3Z7wUOO8VG1XUM8q+9WkN0zopma0Gqy1wGg1uQUG8qj3fMlgzCyEuxk9JXVHzFob05c0CBvNcz5YS0f2q6T73W/OFx3BCzucxLudQkgldcp06w3ZDnFtcFVNOnO8j5nFjMjZFefA+Mf/mNWSIPyfm2CzXv4lRjN0rKBELB6w2pS2kU82RPh7DYjf0khHzarfmlC4HPiGHO78V8vFKG8g2fJpH1uGCxAiiue0bkfmkXoqn4AVQe3p/jMf++084QoZfWisOA0WqsR5wKqTU7UXS7Yi27MO34cq+IQ4l0JHJUZiPnThEyv1oyMTRUPfOCly828ogy/P+91jwsJ1zOqlFU/jyHcGaUsLzMp01vbTIBOcU6YCPOnnT3zdBuWkBljzA0ILHA9qOxhcLfGZKuCWHtmQqo7plXlTHxq+alkjWjUHdz8BTVPj8Xefiq3fAwaN/KEFtBF9PToNTXivRZFZkrRYH0CORIDaIAe8ssdaQUFrNdeqBObuow5EXXqnuMIhyNV+JS3ZKi1UegNZvK+Fea5MnJmcH6YL9nai765e1+j/8spiuB4VM5wM0nWZ94QgPfIXfNIkxVNHKltWMc6EJqIIGsfj5/WaKC2QT2pDFDTk6m57t+GDmEfywbqfbthsebDS34NyPht56G/Ajk3pDRbqDw=
  on:
    distributions: sdist bdist_wheel
    repo: Horta/ncephes
