python: 3.6
language: python
env:
  global:
  - PKG_NAME=ncephes
  - CIBW_SKIP="cp34-* cp35-* *i686*"
  - CIBW_BEFORE_BUILD_LINUX=ci/before-build-linux
  - CIBW_BEFORE_BUILD_MACOS=ci/before-build-macos
  - CIBW_TEST_COMMAND="python -c \"import $PKG_NAME; import sys; sys.exit($PKG_NAME.test())\""
matrix:
  include:
  - sudo: required
    services:
    - docker
  - os: osx
    language: generic
    before_install:
    - brew update
    - brew outdated python || brew upgrade python
    - brew unlink python && brew link python
    - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
    - hash -r
    - python -m pip install --upgrade pip setuptools wheel
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
    - cmake
install:
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/hcephes/master/install)
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
- python -m pip install cibuildwheel>=0.9.2
- cibuildwheel --output-dir wheelhouse
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: DJKRU7OwO19VcR37FkuaeVLGzEte9DrqIHirNIlDcyGPQau4GSkBsMzadl7V1xjWqe4snxDPkNNRDfuZHgt6KpJKScn+V7jwaUiHK4s2vJIV/i6Vq+KVc1MklBvgiS8R87QkD8bfXK9OSI5Zk8p/P0g1oD183a4lDpP2/hAtmbrdQbi9/wwW4lHSyrnUvpyiOCejML7jHlTVSqhKxG8s8ITnohbF+8KkZ7786U1msutpSP4DSOYaldlBmIOL5yJDlxw9vgKpPwyIolV72OTkXgaQHHO/nqufEMQuY8xqEAJ2E1hL+hd0dCBWK1QDOppYK8TUcnTyxcW5eG2spWVXcver8lJGSsZUukfQPKIksHSpQnghuk1kKd1KYdsiFYEhgakQp33M59VOJS2gvnHo9/PnsU2GufmVoT5EIEgY1V8bsc4KFf51xbzSFfuzlZoT+SWtCIkXTE+F9YdcgVYPVAAw7dKKteNahO9PJQxyUQX21tC45RvwCMO4bC7GFqRG060IaCu0Rb5FmBtVnhmMoKylmqYy2VRL1D3Zd4HeslvFV09Rfe1cDs8iwmV93rjK74NKctGnbj35NJcPT/cYgw3yYUowj05zwBJvZMPYfFU7Ud55YFKZEhrJbUxiq/HaI3/qb//qu8TXTTjZ9slyzPVmvtaGOGjK06Mq35T1iVE=
  on:
    tags: true
    repo: limix/ncephes
    branch: master
    python: 3.6
