language: python
sudo: required
dist: trusty
services: docker
git:
  depth: 5
cache:
  pip: true
  directories:
  - $HOME/Library/Caches/Homebrew
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
  - env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - os: osx
    osx_image: xcode8.3
    language: generic
    env: PYENV=py27
before_install:
- travis_retry bash <(curl -s https://raw.githubusercontent.com/limix/travis-tools/master/get-travis-tools.sh)
- travis_retry travis/before-install.sh
script:
- travis_retry travis/script.sh
after_success:
- travis_retry travis/after-success.sh
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: l5wskb3nGaiZHVvHSTRUdniwYN998vWhv07sS3Kk/dA2mNsSMPyVzR+kjrEXDMnrlm4X03H590yH3rSb0v6TDDU+n7sdNhIuRa3h0CkgEHyFdIWGiQuKcMNKH2P6xWK/q4o/f9+C5cTo976KyXLkG7SFqPcHtvPWvWD7aa4MQxgt3tjLCFHATv9peK/FmUnJtcR1QOqiMjs3IM+qfeqcsBoYe1biqQtmdRzTGmbYWAtGBy1ftJKoUiCK58axYwGjkdBomDPV2iw75JqcXx18DehuzVE0ayyU3V+oCMyej9u+RIRmMDHjs0t0T7XsJoUey4EZYsrWwMJhXuPUnZqAhkpRRAddxwHMl8Be3Go8WXcEjvjszyyDDAIXTySXReomzWy1idHjTA8h3eFkyYCAQHsTl8ea3OCnlvn3DyfBAjJBOjTJN1Nk36Cu1P8f+N2Z0fquYjFZeh0Yk1c+VnV3dI1xJxtfHePNh8/DbC5zyRcoqmcS9F0h7zVcKSj9YtnsadhrpssdDGLPjKjq/fci60/j92UvfTjhe58xo714dlUTkvIr5ShgEZxkU6MNz3RwAfVCK1qP+HREpHuXRf0ZM+86NmIIT3Rg3SEP1ztlBxp+zLblbq7XYwNs+DeFG3xEDB+DrHbVyiCs0rMiWQRN6R4gXP6oav9+qCmhFjjW6rk=
  on:
    repo: limix/ncephes
    branch: master
    tags: true
env:
  global:
    - secure: owCfm9AyRjHJJDwvG4jIoYD+7cxntbRRMRPPvvgY7f66FFsVHQkl8kHhcW9F7UTONzIPs1Ij+xzaY27mxQpQHX4Kt4I6NteAjv8eKmi2RUN5MVoddc7m05DbKfBufJ+EtpSFaTufsXxRb2m7/5nXQRDH0y6yOWrg6PCrSmrqR80UQdQBBqnuFj92dV4e1wgJjKF7BXdjIqZ8u+yOFkwb0Q0u9CsTh5pnsYeW8UYMgkQ7HgekUpuYMvjRXm0CNxICHSe8VuhzHCCGvdlGr7URdEhrWAUIq1Km0R0KV7vwS2WSO1bX0C369wozWD59K/mdx3nhK2TJF29PGE03/jTsdmqREyRhbprwoKZGF9vTjj4EX4oKnrTd7E1Yh7FWZtv+5uCwAFq0QoCU/FuTWo2jMcwkPVAmXDEzJ4523vk5lIo2Ulk6X9R5jbapxYyMHP6RXhKjgSfEpBkOXX4YcRu8Ywd8tKUGbLLF1KnFWYZXsu+QjWwFnK+NB/gM+aSWKMsfShfWazThAK0PYPp/E4NW8EnyEqIVOVAQxtRtmuOdfCP6AjKRh7ys5qOvjHcXkrW+BcnWh7w3Pc2YxDknvtqncNF7eDSNyfRkRHPRB/kwVtwfTaXpbfRbheeQyy/AWLcz1D/HnvroA5yJkC4nlpC7AF0wa7GgJaIIfoyhzjHgItA=
    - PKG_NAME=ncephes
