language: python

matrix:
    include:
        # - os: linux
        #   sudo: false
        #   dist: trusty
        #   python: 2.7
        # - os: linux
        #   sudo: false
        #   dist: trusty
        #   python: 3.4
        # - os: linux
        #   sudo: false
        #   dist: trusty
        #   python: 3.5
        - os: osx
          language: generic
          env: TRAVIS_PYTHON_VERSION=2.7
        # - os: osx
        #   language: generic
        #   env: TRAVIS_PYTHON_VERSION=3.4
        # - os: osx
        #   language: generic
        #   env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh -O install.sh
    - chmod +x install.sh
    - ./install.sh

install:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda install pycparser -y --name travisci
    - source activate travisci
    - python setup.py develop

script:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - source activate travisci
    - py.test .
