language: python
dist: trusty
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
    - wget https://raw.githubusercontent.com/Horta/travis-miniconda/master/install.sh -O install.sh
    - chmod +x install.sh
    - ./install.sh

install:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - source activate travisci
    - python setup.py develop

script:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - source activate travisci
    - py.test .
