dist: trusty
matrix:
  include:
  - env: PYTHON=2.7 NUMPY="numpy=1.10"
  - env: PYTHON=3.4 NUMPY="numpy=1.10"
  - env: PYTHON=3.5 NUMPY="numpy=1.10"
branches:
  only:
  - master
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=$HOME/miniconda3/bin:$PATH
- conda update --yes conda
- conda create -n travisci --yes python=$PYTHON $NUMPY cffi pip scipy jinja2 numba
- source activate travisci
- CONDA_INSTALL="conda install --yes -q"
- PIP_INSTALL="pip install -q"
install:
- python setup.py build_ext -q --inplace
- python setup.py install -q >/dev/null
script:
- python setup.py test
notifications:
  email: false
  on_success: change
  on_failure: always
deploy:
  - provider: releases
    api_key:
    secure: NTk61XWFLYJcRuly7iS1/mSZ5Udj5oS7JGRgJh+vSaRnPGW2WAqePyts8b+JJ4C69ygieGmBnRsb7NyI3seCXEwUnxBw0HwY+zm3fDUbgzBmzv3Q4hCGgojWrk0zahacnW0yghRn/onGLAWpNAG+EfptfkQtzjBahK8F0Tji+A+l5MpmZODp7nh/njWlQd2dHnjZIVmfyu53tGXZT3eOdWBpe5Yy6cODBN72nWJWJIGZ5hFrdmlt9c17ZIJc8IOtogZWN0fWfiL4ncQDFUjBaxjjLzyNVdtCJBCYhFfZysuNKviGhitfEfNQnOMfuoc6lFB6C407oQsJ92/MX8PKHsSn4zpSosrz5VHG4b3Qujkcn5iK3LyfRY9yoeh88gBGiCU+4JYEXWq7b1LOPOfQ09fZ6F8evIiSJCcY6zdlv6nZ/GYvVroZP1JXrmYDfH86mw/g9y1S/YKPLOCbqYcwCjvWcIqpiD92B8yYNpTujkqqIoRvVaHdweawPQBfncB5RrLlCjnNA0Ic7at5rjkRt8Hy5ZyjR0yrgExICGGUGxnHMZZ+k94tpJQHRPRkd/g29+woHIo1EN1XKWRZfKiSoZ91AOBI1Na8HYALDE6toJhfYQOOEb8DhoCV1IJXLoHCP4Dqzu1QfP7ebnpzxV6aDIdNzI3k6uzZtLZVbgt/9dA=
    file: dist/ncephes-0.0.4.tar.gz
    on:
      repo: Horta/ncephes
    skip_cleanup: true
  - provider: pypi
    user: danilo.horta
    on:
      tags: true
    skip_cleanup: true
    password:
      secure: gMlG6N23UCkxndWq9gItUF3XiKOQ0l5pZGEQEvjy5KHYA8py6jnjR03hu+36o23AQMLJaLbebJl0aoBinDbNhcSidHzzeWfvVAj9Z4AXZC2augLurgsRP+WJwafBBtKOMy1Wcyn+pwhFBlgXaHFbKax2EGKZ9mZPN1BeLbGwKCQx8GHH41tex1ZlacqiI3D2msQijN91jexaLmMP8rjch7xdLZOf2WjKEUaP/yb3ubNIv+XcA6ch4I0F04TKGsFaIVfAGW3gSPen4GKN+Bm84SBxdKOH0rWmxCqXAD49MNmBiow4jlmuM148X6LfZV3ob7n2NSPgMW4ZUHexWI14MPlT/tH9zPr33BJ9t+4h+Rik55cAAMRu/2jrLmSV0NLaG7nwPK0NjYxHkSK3z6PiAUW8n2m2o48Bdao0YrQurHEAz34cU+1hndAiHOP6AO1cjTahmDI67Jr0M7e70ggLNcmBNzM2vfq+K8duYc49ewlgIMT+hNR6HQFAX0D1FlyKbEwG1ZoC1EYp7t2KGDcSeWYUxXjqh1eJOm5XFlBl5OkBQALLd6SMAehaAAcXhWeu2prmqXQ0CKxpQUcEz/DYWpYls6+S3qa5THVSjvDpl92wB9kpPOsM6+TpVPBd2X+ExFAIn4TuIn6n+6R7js/qBBQZWjoHWP6xVBQUHT+3vMU=
