language: python
sudo: required
dist: trusty
git:
  depth: 5
before_install:
- sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.8
  main' || true
- wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add - || true
- sudo apt-get update -y || true
- sudo apt-get install -qq -y clang-3.8 zlib1g-dev libbz2-dev || true
matrix:
  include:
  - os: linux
    python: '2.7'
    compiler: clang-3.8
    env: LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
  - os: linux
    python: '3.5'
    compiler: clang-3.8
    env: LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
script:
- if [ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]; then pip install enum34; fi
- pip install pypandoc
- git clone https://github.com/numba/llvmlite.git --depth 1
- pushd llvmlite
- CXX_FLTO_FLAGS= LD_FLTO_FLAGS= python setup.py install
- popd
- python -c "from pypandoc import download_pandoc as dp; dp(targetfolder='~/bin/');"
- export PATH=~/bin:$PATH
- ~/bin/pandoc -v
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import ncephes; ncephes.test()"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: O999CaZ56Sl1QiTObeGFVZaP0+VRDO/W2rbUXYNKgPFeMlYLtvyiNTOB/ZkBIR+sXtksDMPTGJikpP1SfgNKVB/5MZbSOLaEHKpnX6uOQ8sGcnTYJiNI+4d//nttJCuuOZdGFijT4+EkV/CGF4W+dJ2+6RoOalMWzr6qaswkxMQuNJPim4iWpUIuBozoKkqVjJlzBXV5Zlopami3AZOqpEbKi67GMIFJbM8v8KVFZWoU09p7Ze/Q3uZ9d8xM+7utJXQhQOrd9venEZ+O3+J0Y6cHjs173FkJp15Y3mTmWWhrMiFBqSpvzfPTgYyUsp2njElarq2xty/ET7jDnp6mRrgxlTtnl3nAWyPKfzJqPIf+fK/vsIF/ELCam5hKeT3qqcJsKRAcFzP/AlCaUYEGn9nIE6/W/2ciFmRQgfAmPuYKBWexWLso7vDdSw6KqkXJwxDjleoy+mjxvFO7ZhTI2kRbv8TKSH8phRaug9l9SIMQznFd4Q8+D59W+oUtbMRfZMDVPJ7e6rCF5MIfCzNB2LabCVeL/a3p/OfScBhPQYXYPSyMvRyaNn/J7UmUWVKv3wEno1TCWCaj0YfZ/fMPrGtfG9olaXdY5DTN/+n5QXf93MOLF3tcXIFDQj/ZvCeZF8VsAP+iFPLhuijQFTfz08o9gPIFdij20Yr8XkhOmSY=
  on:
    distributions: sdist bdist_wheel
    repo: glimix/ncephes
