dist: trusty
matrix:
  include:
  - env: PYTHON=2.7 NUMPY="numpy=1.10"
  - env: PYTHON=3.4 NUMPY="numpy=1.10"
  - env: PYTHON=3.5 NUMPY="numpy=1.10"
branches:
  only:
  - master
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=$HOME/miniconda3/bin:$PATH
- conda update --yes conda
- conda create -n travisci --yes python=$PYTHON $NUMPY cffi pip scipy jinja2 numba
- source activate travisci
- CONDA_INSTALL="conda install --yes -q"
- PIP_INSTALL="pip install -q"
install:
- python setup.py build_ext -q --inplace
- python setup.py install -q >/dev/null
script:
- python setup.py test
notifications:
  email: false
  on_success: change
  on_failure: always
deploy:
  provider: pypi
  user: danilo.horta
  on:
    tags: true
  skip_cleanup: true
  password:
    secure: gMlG6N23UCkxndWq9gItUF3XiKOQ0l5pZGEQEvjy5KHYA8py6jnjR03hu+36o23AQMLJaLbebJl0aoBinDbNhcSidHzzeWfvVAj9Z4AXZC2augLurgsRP+WJwafBBtKOMy1Wcyn+pwhFBlgXaHFbKax2EGKZ9mZPN1BeLbGwKCQx8GHH41tex1ZlacqiI3D2msQijN91jexaLmMP8rjch7xdLZOf2WjKEUaP/yb3ubNIv+XcA6ch4I0F04TKGsFaIVfAGW3gSPen4GKN+Bm84SBxdKOH0rWmxCqXAD49MNmBiow4jlmuM148X6LfZV3ob7n2NSPgMW4ZUHexWI14MPlT/tH9zPr33BJ9t+4h+Rik55cAAMRu/2jrLmSV0NLaG7nwPK0NjYxHkSK3z6PiAUW8n2m2o48Bdao0YrQurHEAz34cU+1hndAiHOP6AO1cjTahmDI67Jr0M7e70ggLNcmBNzM2vfq+K8duYc49ewlgIMT+hNR6HQFAX0D1FlyKbEwG1ZoC1EYp7t2KGDcSeWYUxXjqh1eJOm5XFlBl5OkBQALLd6SMAehaAAcXhWeu2prmqXQ0CKxpQUcEz/DYWpYls6+S3qa5THVSjvDpl92wB9kpPOsM6+TpVPBd2X+ExFAIn4TuIn6n+6R7js/qBBQZWjoHWP6xVBQUHT+3vMU=
