language: python
sudo: required
dist: trusty
git:
  depth: 5
cache: pip
matrix:
  # include:
  # - python: 2.7
  #   env: NUMBA="false" "PATH=~/bin:$PATH"
  # - python: 3.5
  #   env: NUMBA="false" "PATH=~/bin:$PATH"
  # - python: 3.6
  #   env: NUMBA="false" "PATH=~/bin:$PATH"
  # - python: 2.7
  #   compiler: clang-3.8
  #   env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
  #     "PATH=~/bin:$PATH"
  # - python: 3.5
  #   compiler: clang-3.8
  #   env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
  #     "PATH=~/bin:$PATH"
  # - python: 3.6
  #   compiler: clang-3.8
  #   env: NUMBA="true" LLVM_VERSION="3.8" CXX="clang++-3.8" LLVM_CONFIG="llvm-config-3.8"
  #     "PATH=~/bin:$PATH"
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 NUMBA="true"
before_install:
- travis_retry travis/before_install_stage.sh
install:
- travis_retry travis/install_stage.sh
script:
- travis_retry travis/script_stage.sh
after_success:
- travis_retry travis/deploy_wheels.sh
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: l5wskb3nGaiZHVvHSTRUdniwYN998vWhv07sS3Kk/dA2mNsSMPyVzR+kjrEXDMnrlm4X03H590yH3rSb0v6TDDU+n7sdNhIuRa3h0CkgEHyFdIWGiQuKcMNKH2P6xWK/q4o/f9+C5cTo976KyXLkG7SFqPcHtvPWvWD7aa4MQxgt3tjLCFHATv9peK/FmUnJtcR1QOqiMjs3IM+qfeqcsBoYe1biqQtmdRzTGmbYWAtGBy1ftJKoUiCK58axYwGjkdBomDPV2iw75JqcXx18DehuzVE0ayyU3V+oCMyej9u+RIRmMDHjs0t0T7XsJoUey4EZYsrWwMJhXuPUnZqAhkpRRAddxwHMl8Be3Go8WXcEjvjszyyDDAIXTySXReomzWy1idHjTA8h3eFkyYCAQHsTl8ea3OCnlvn3DyfBAjJBOjTJN1Nk36Cu1P8f+N2Z0fquYjFZeh0Yk1c+VnV3dI1xJxtfHePNh8/DbC5zyRcoqmcS9F0h7zVcKSj9YtnsadhrpssdDGLPjKjq/fci60/j92UvfTjhe58xo714dlUTkvIr5ShgEZxkU6MNz3RwAfVCK1qP+HREpHuXRf0ZM+86NmIIT3Rg3SEP1ztlBxp+zLblbq7XYwNs+DeFG3xEDB+DrHbVyiCs0rMiWQRN6R4gXP6oav9+qCmhFjjW6rk=
  on:
    repo: limix/ncephes
    branch: 1.0.x
env:
  global:
    secure: C1z5JnOUOjgNE6oH+yV1apsWTFH7D4i3ZbM9SYwfSIweSYVw2MVZiQ8ZuZX7GIt6/K7y50x1CCh31xavFxdI3dvYv8GjC1MvGezDu+sv7e74hgmm7PbOwfaDA4zl0UyurR1o+S2xiSc5tNKCNeHpxKyDeRjD4TOQMtoutkVcp64Wc1JWZb1ezYdLfAegp7klqoDfU9kzk3ygfvvi3k7RX2JTXgk8vVNReiLI+EM5VwB6303OG7vKhjXvkjTTRnDezhDTdO/VHHtr2V7X/DGKecTLZt8iWsLEzjN81eRm5iHcbwzsJ+Rhow6BYmNAy+zZfuZ5tXKTGP6HO5wAVWIuMoA29lvB02vtM2jRzaQU7IYQcIXAmxiBMz8gjhHmdnemTHdNPENljs6uLhE1j6yTXq3k9jedkXas5prvT+vffgsVcnx9lOwpJFF0/M/rs6/hB4z2vGKbCU98mJj514DJISMXKqxLJ63KpS9ftUg0xpjar5Axz8q494NODY/t88SQB0CtMY5ibinnt+Gudo5S3Jk9qUX6S9Qio/L/3QsN+PUOO1q2k6wIYeCyFSU2vic6+xc46g0w9nqWVutrM8uULm3vmuA/4zuCUCX2q5XfjygHgtNA+vcWZyVV54P+Pow2Rfmmugrr+GVulIvLz/SiWfyHJFLUBWEKdhOnynowOtU=
