image: Visual Studio 2015
os: Visual Studio 2015

environment:

  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  # Workaround for https://github.com/conda/conda-build/issues/636
  PYTHONIOENCODING: "UTF-8"

  # this is how to allow failing jobs in the matrix
  matrix:
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      PY_CONDITION: "python >=2.7,<3"
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "34"
      PY_CONDITION: "python >=3.4,<3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"
    - TARGET_ARCH: "x64"
      CONDA_PY: "35"
      PY_CONDITION: "python >=3.5"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"

platform:
  - x64

# scripts that run after cloning repository
install:
  # Set the CONDA_NPY, although it has no impact on the actual build. We need this because of a test within conda-build.
  - cmd: set CONDA_NPY=19

  # Remove cygwin (and therefore the git that comes with it).
  - cmd: rmdir C:\cygwin /s /q

  - cmd: set "OLDPATH=%PATH%"
  - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
  - cmd: conda update --yes --quiet conda
  - cmd: set "PATH=%OLDPATH%"
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --set show_channel_urls true
  - cmd: conda update --yes --quiet conda
  - cmd: conda install --yes --quiet obvious-ci conda-build-all vc=14 numpy numba
  - cmd: conda install --yes --quiet conda-forge-build-setup
  - cmd: run_conda_forge_build_setup

build: off

test_script:
  - cmd: python setup.py test
